<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zacchaeus Gilbert">

<title>Claims and Reserves Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Claims_Reserves_Analytics_files/libs/clipboard/clipboard.min.js"></script>
<script src="Claims_Reserves_Analytics_files/libs/quarto-html/quarto.js"></script>
<script src="Claims_Reserves_Analytics_files/libs/quarto-html/popper.min.js"></script>
<script src="Claims_Reserves_Analytics_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Claims_Reserves_Analytics_files/libs/quarto-html/anchor.min.js"></script>
<link href="Claims_Reserves_Analytics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Claims_Reserves_Analytics_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Claims_Reserves_Analytics_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Claims_Reserves_Analytics_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Claims_Reserves_Analytics_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Claims and Reserves Analytics</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Zacchaeus Gilbert </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Welcome to the second part of my “Actuarial Packages” project! Here we are going to take a quick look at what R/R studio can do in regards of “Claims and Reserves”! If we were discussing topics for the SOA before, then this brief discussion will look at a topic to contribute to the Associate of the Casualty Actuary Society (ACAS), which is a part of…</p>
<p><img src="Pictures/CAS.png" class="img-fluid"></p>
<p>Let’s start by loading some packages again…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ChainLadder) <span class="co"># This is all we need :)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>…packages, more like, “package”; it is pretty surprising, but with how up-to-date <code>ChainLadder</code> is, a lot of talking points and visualizations can be done with just this package.</p>
</section>
<section id="claims-and-reserves" class="level2">
<h2 class="anchored" data-anchor-id="claims-and-reserves">Claims and Reserves</h2>
<p>Like before, feel free to use tab completion on the next code chunk to look around at the many datasets and functions within <code>ChainLadder</code>!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ChainLadder::</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After looking around, you might notice…</p>
<p><img src="Pictures/triangles.png" class="img-fluid"></p>
<p>There is a lot of mentions of “triangles”, but what is a triangle in this context? An “Actuarial Triangle” is the ongoing record of how much money a company is keeping in “reserves” for the many possibilities of an individual making a claim during a given period of time. Like before, a company has to deal with risk assessment as they do not know when an outcome is going to happen for several individuals, but in this case, actuaries need to assess the probability of individuals making a claim (or possibly letting the policy expire); this also needs to take into consideration several expenses that can occur as time passes. Here is a visual to help demonstrate this…</p>
<p><img src="Pictures/Reserves.png" class="img-fluid"> Credit to… <img src="https://youtu.be/wyYp2R1toW8?si=YBQ4hR3_9fovoqpO.png" class="img-fluid"> for the picture; feel free to watch her video over this topic too (it’s great)! But still, why a “triangle”? To help answer this, let’s take a look at a General Insurance data set called <code>GenIns</code>. The <code>GenIns</code> data set will already be in the form of a matrix that is specifically a “triangle”; <code>ChainLadder</code> has a special <code>show()</code> function that will take the matrix and display it in a typical Actuarial Triangle. Let’s do that…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show</span>(GenIns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      dev
origin      1       2       3       4       5       6       7       8       9
    1  357848 1124788 1735330 2218270 2745596 3319994 3466336 3606286 3833515
    2  352118 1236139 2170033 3353322 3799067 4120063 4647867 4914039 5339085
    3  290507 1292306 2218525 3235179 3985995 4132918 4628910 4909315      NA
    4  310608 1418858 2195047 3757447 4029929 4381982 4588268      NA      NA
    5  443160 1136350 2128333 2897821 3402672 3873311      NA      NA      NA
    6  396132 1333217 2180715 2985752 3691712      NA      NA      NA      NA
    7  440832 1288463 2419861 3483130      NA      NA      NA      NA      NA
    8  359480 1421128 2864498      NA      NA      NA      NA      NA      NA
    9  376686 1363294      NA      NA      NA      NA      NA      NA      NA
    10 344014      NA      NA      NA      NA      NA      NA      NA      NA
      dev
origin      10
    1  3901463
    2       NA
    3       NA
    4       NA
    5       NA
    6       NA
    7       NA
    8       NA
    9       NA
    10      NA</code></pre>
</div>
</div>
<p>Tada! Pretty cool! Now let’s start breaking down what this all means. On the top-left corner, we have two terms, “dev” and “origin”. “dev” stands for “development”, which means that as time passes, the company that issued the policy is able to learn more information regarding the holder and the potential changes to the policy (claims? expenses?). The company understands more, so we say that the policy has “developed”. Then there is “origin”, which simply is the time that the policy was first issued. In this case, <code>GenIns</code> information was recorded on a monthly basis. Now we can infer the reasoning behind the triangle; if a policy was bought within the first month and ten months pass, then that policy has had a total of ten development periods. Meanwhile, if a policy was bought within the tenth month, then that policy has only had the one month to develop.</p>
<p>Now, you might be wondering, there are a lot of NAs, is there something that we can do with those? And, yes! We can take advantage of the trends between development periods to infer what development could look like for policies that were purchased later. Notice for a policy of origin ten, there are nine other policy origins that we can infer a trend from. Let’s start by looking at the development periods between one and two for a policy of origin one; they are keeping $357,848 in reserves for this. Then after one development period (so looking at development period two now), they now are keeping $1,124,788; we can infer something here. There was actually an increase in what is being kept in reserves by a ratio, and this ratio can be derived with arithmetic…</p>
<p><span class="math display">\[\frac{1,124,788}{357,848} = 3.14.\]</span>This ratio is called its “Loss Development Factor” (LDF). We can keep doing this for every origin period up to origin nine…</p>
<p><span class="math display">\[\frac{1,363,294}{376,686} = 3.62.\]</span>Then, we can find the average of all the LDFs and use that average to then multiply the reserves in origin ten by that average. We could continue doing this for every transition into different development periods for every origin period to fill the rest of the Actuarial Triangle; this inferential strategy is called, “Chain Ladder Reserving”. We could go through the grind to calculate all of our LDFs, but conveniently enough, this package has a function for calculating the LDFs for us; this function is called <code>ata</code>. Let’s use the function and see what happens…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ata</span>(GenIns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      dev
origin   1-2   2-3   3-4   4-5   5-6   6-7   7-8   8-9  9-10
  1    3.143 1.543 1.278 1.238 1.209 1.044 1.040 1.063 1.018
  2    3.511 1.755 1.545 1.133 1.084 1.128 1.057 1.086    NA
  3    4.448 1.717 1.458 1.232 1.037 1.120 1.061    NA    NA
  4    4.568 1.547 1.712 1.073 1.087 1.047    NA    NA    NA
  5    2.564 1.873 1.362 1.174 1.138    NA    NA    NA    NA
  6    3.366 1.636 1.369 1.236    NA    NA    NA    NA    NA
  7    2.923 1.878 1.439    NA    NA    NA    NA    NA    NA
  8    3.953 2.016    NA    NA    NA    NA    NA    NA    NA
  9    3.619    NA    NA    NA    NA    NA    NA    NA    NA
  smpl 3.566 1.746 1.452 1.181 1.111 1.085 1.053 1.075 1.018
  vwtd 3.491 1.747 1.457 1.174 1.104 1.086 1.054 1.077 1.018</code></pre>
</div>
</div>
<p>Great! Notice that our two answers from before are present, and the function calculated every LDF for us! The “dev” header now displays the transition between one development period to the next one as well. And I mentioned that we could calculate the average LDFs for between each development period to infer reserve estimates, well those averages are on the 2nd bottom row labeled as “smpl”, which stands for “simple” as in a “simple average”. The bottom-most row is labeled as “vmtd” which stands for “volume weighted average”, which is a more complex average that considers the conditional probability of more age-to-age factors; feel free to explore this topic more by typing <code>?chainladder</code>!</p>
<p>Now we’re going to take the time to explore one more function within this package, the <code>MackChainLadder()</code> function; everything that I have explained regarding the “Chain Ladder Reserving” technique has been working with “Mack Chain Laddering” actually. The <code>MackChainLadder()</code> functions gives us a way to visualize the residuals that occur with using this reserve estimation technique; as you will see, this will be very powerful to demonstrate the increasing variance and uncertainty that comes from making several layers of “inferences of the inferences”. With this being said, let’s look at <code>MackChainLadder()</code>! All we have to do is state the triangle that we’re using, type in “Mack” for the <code>est.sigma</code> (you may remember that <span class="math inline">\(\sigma\)</span> represents standard deviation), and then put the whole function through <code>plot()</code> and…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Insurance <span class="ot">&lt;-</span> <span class="fu">MackChainLadder</span>(GenIns, <span class="at">est.sigma=</span><span class="st">"Mack"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Insurance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Claims_Reserves_Analytics_files/figure-html/MackChainLadder-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(Insurance) <span class="co"># Just removing this to keep environment clean.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Perfecto! Notice how with every forecast for the origin period, there is an increase in deviation from each average that is calculated; the bar charts indicate the increasing window of variance through its widening gaps between stems and the line charts show more variance through its differing trends to represent the increase in range for its confidence intervals.</p>
<p>And that wraps up the discussion on “Claims and Reserves”! As you can see, there is a lot packed into <code>ChainLadder::</code> even though it was the only package that we needed to load to do this much; there are actually many functions within this package that allows you to convert data sets into “triangles”, so definitely check those out if you find yourself following the ACAS pathway!</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>